### ISSUE TITLE
app-functions-azure does not start due to sintax error

### ISSUE THREAD

**Issue by kurokobo** [edgexfoundry-holding/app-service-examples#11]
After successful of `make` of  `app-functions-azure`, I got a `syntax error` when I start `app-service`.

```
$ make app-services/app-functions-azure 
CGO_ENABLED=1 GO111MODULE=on go build  -o app-services/app-functions-azure/app-service ./app-services/app-functions-azure

$ cd app-services/app-functions-azure/
$ chmod +x app-service 
$ ./app-service 
./app-service: line 1: syntax error near unexpected token `newline'
./app-service: line 1: `!<arch>'
```

As I replied in Slack channel, this is caused by the definition of the package name as shown below.

https://github.com/edgexfoundry-holding/app-service-examples/blob/98df401a5ae95c74f91fb62ba95281a6b99360a5/app-services/app-functions-azure/main.go#L1

In my understanding, in terms of Golang, the package name has to be `main` when we build the package as an executable file. If the package name is not `main`, the package will build as an external library.

**Comment by lenny-goodell** [comment]
Fixed by #12
