### ISSUE TITLE
Examples don't run as is without configuration

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry-holding/app-service-examples#20]
The original intention of these examples was to enable a build and run so as to focus on being able to leverage the SDK. Currently, all examples assume the secure version of EdgeX is running and require an environment variable to disable security which isn't documented anywhere in these examples. We should update the examples (with the exception of the "security" examples) to assume non-secure mode of edgex for simplicity.

**Comment by rsdmike** [comment]
I think we should check in the .vscode folder with the ENV variable set to false and can be easily changed. Can check into the .idea folder to if those settings are in there.

**Comment by lenny-goodell** [comment]
> I think we should check in the .vscode folder with the ENV variable set to false and can be easily changed. Can check into the .idea folder to if those settings are in there.

Don't assume everyone is using VSCode.... ;-)

**Comment by lenny-goodell** [comment]
This was resolved by #38
