### ISSUE TITLE
App Service Example logging client nil pointer deference

### ISSUE THREAD

**Issue by adam-intel** [edgexfoundry-holding/app-service-examples#32]
On line 52 there is a possibly nil pointer deference.

https://github.com/edgexfoundry-holding/app-service-examples/blob/62b7d383b9e32894ebe625f6b8a0efd0db0428ff/app-services/cloud-event-transforms/main.go#L48

**Comment by lenny-goodell** [comment]
With Geneva the edgexSdk.LoggingClient is `never nil` after returning from Initialize so the check for nil is no longer needed.

**Comment by lenny-goodell** [comment]
No sure why the code is using info.... in the else case... This does need to be cleaned up.
